origin: nasa
base_name: gesw1_bqds
jobs:
- endpoint: earth_image
  param:
    lon: 20
    lat: 30
    dim: 22
body: 
output_table: "nasa_image"
output_mode: overwrite
extraction_column: "ARQPIB_FEC_PART"
curated_layer: false
final_layer: master
date_format: "%Y%m%d"