origin: nasa
base_name: gesw1_bqds
jobs:
- endpoint: technologies_search
  param:
    search: "engine"
    perpage: 10
    page: 0
body: 
output_table: "nasa_technologies"
output_mode: overwrite
extraction_column: "tech_id"
curated_layer: false
final_layer: master
date_format: "%Y%m%d"


 